#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonschema
Version  : 3.0.2
Release  : 52
URL      : https://files.pythonhosted.org/packages/92/d2/8768983d6e4bb1478ea08e7bc186304f47b99c22bfd711caa8e9becb0361/jsonschema-3.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/92/d2/8768983d6e4bb1478ea08e7bc186304f47b99c22bfd711caa8e9becb0361/jsonschema-3.0.2.tar.gz
Summary  : An implementation of JSON Schema validation for Python
Group    : Development/Tools
License  : MIT
Requires: jsonschema-bin = %{version}-%{release}
Requires: jsonschema-license = %{version}-%{release}
Requires: jsonschema-python = %{version}-%{release}
Requires: jsonschema-python3 = %{version}-%{release}
Requires: attrs
Requires: idna
Requires: jsonpointer
Requires: pyrsistent
Requires: rfc3987
Requires: setuptools
Requires: six
Requires: webcolors
BuildRequires : attrs
BuildRequires : buildreq-distutils3
BuildRequires : funcsigs
BuildRequires : idna
BuildRequires : jsonpointer
BuildRequires : pyrsistent
BuildRequires : python-mock
BuildRequires : rfc3987
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : six
BuildRequires : webcolors

%description
jsonschema
        ==========
        
        |PyPI| |Pythons| |Travis| |AppVeyor| |Codecov| |ReadTheDocs|

%package bin
Summary: bin components for the jsonschema package.
Group: Binaries
Requires: jsonschema-license = %{version}-%{release}

%description bin
bin components for the jsonschema package.


%package license
Summary: license components for the jsonschema package.
Group: Default

%description license
license components for the jsonschema package.


%package python
Summary: python components for the jsonschema package.
Group: Default
Requires: jsonschema-python3 = %{version}-%{release}

%description python
python components for the jsonschema package.


%package python3
Summary: python3 components for the jsonschema package.
Group: Default
Requires: python3-core

%description python3
python3 components for the jsonschema package.


%prep
%setup -q -n jsonschema-3.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567192700
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsonschema
cp COPYING %{buildroot}/usr/share/package-licenses/jsonschema/COPYING
cp json/LICENSE %{buildroot}/usr/share/package-licenses/jsonschema/json_LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jsonschema

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsonschema/COPYING
/usr/share/package-licenses/jsonschema/json_LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
